CREATE TABLE USUARIO (
  idUSUARIO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE TEXT NULL,
  ROL ENUM(1,2,3) NULL,
  PRIMARY KEY(idUSUARIO)
);

CREATE TABLE AMBIENTE (
  idAMBIENTE INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE TEXT NULL,
  CUENTADANTE INTEGER UNSIGNED NULL,
  PRIMARY KEY(idAMBIENTE),
  FOREIGN KEY(CUENTADANTE)
    REFERENCES USUARIO(idUSUARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE EQUIPAMIENTO (
  idEQUIPAMIENTO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idAMBIENTE INTEGER UNSIGNED NOT NULL,
  NOMBRE TEXT NULL,
  ESTADO ENUM(1,2) NULL,
  SERIAL TEXT NULL,
  PRIMARY KEY(idEQUIPAMIENTO, idAMBIENTE),
  FOREIGN KEY(idAMBIENTE)
    REFERENCES AMBIENTE(idAMBIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE NOVEDADES (
  idNOVEDADES INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idAMBIENTE INTEGER UNSIGNED NOT NULL,
  FECHA DATE NULL,
  DESCRIPCION TEXT NULL,
  ESTADO ENUM(1,2,3) NULL,
  PRIMARY KEY(idNOVEDADES),
  FOREIGN KEY(idAMBIENTE)
    REFERENCES AMBIENTE(idAMBIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE HNOVEDAD (
  idHNOVEDAD INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idNOVEDADES INTEGER UNSIGNED NOT NULL,
  FECHA DATE NULL,
  DESCRIPCION TEXT NULL,
  PRIMARY KEY(idHNOVEDAD, idNOVEDADES),
  FOREIGN KEY(idNOVEDADES)
    REFERENCES NOVEDADES(idNOVEDADES)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


