CREATE TABLE HNOVEDAD (
  idHNOVEDAD INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idNOVEDADES INTEGER UNSIGNED NOT NULL,
  FECHA DATE NULL,
  DESCRIPCION TEXT NULL,
  PRIMARY KEY(idHNOVEDAD, idNOVEDADES)
);


