BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "NOVEDADES" (
	"idNOVEDADES"	INTEGER,
	"idAMBIENTE"	INTEGER,
	"FECHA"	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"DESCRIPCION"	TEXT,
	"ESTADO"	INTEGER DEFAULT 0,
	"PADRE"	INTEGER,
	FOREIGN KEY("idAMBIENTE") REFERENCES "AMBIENTE"("idAMBIENTE"),
	FOREIGN KEY("PADRE") REFERENCES "AMBIENTE"("idAMBIENTE"),
	PRIMARY KEY("idNOVEDADES")
);
INSERT INTO "NOVEDADES" ("idNOVEDADES","idAMBIENTE","FECHA","DESCRIPCION","ESTADO","PADRE") VALUES (1,1,'2024-08-23 00:46:14','PANTALLA ROTA',0,NULL);
INSERT INTO "NOVEDADES" ("idNOVEDADES","idAMBIENTE","FECHA","DESCRIPCION","ESTADO","PADRE") VALUES (2,1,'2024-08-23 01:45:37','TECLADO LE FALTA UNA TECLA',0,NULL);
INSERT INTO "NOVEDADES" ("idNOVEDADES","idAMBIENTE","FECHA","DESCRIPCION","ESTADO","PADRE") VALUES (3,1,'2024-08-23 02:00:23','SE PUSO EL CASO EN MESA DE AYUDA',0,1);
INSERT INTO "NOVEDADES" ("idNOVEDADES","idAMBIENTE","FECHA","DESCRIPCION","ESTADO","PADRE") VALUES (4,1,'2024-08-23 03:09:32','TODO EN UNO NO FUNCIONA',1,NULL);
INSERT INTO "NOVEDADES" ("idNOVEDADES","idAMBIENTE","FECHA","DESCRIPCION","ESTADO","PADRE") VALUES (5,1,'2024-08-23 03:11:15','SE ENVIA CASO A MESA DE AYUDA',1,2);
CREATE VIEW EQUIRESUMEN AS
SELECT E.IDAMBIENTE,A.NOMBRE AMBIENTE,E.NOMBRE TIPO,CASE WHEN E.ESTADO=0 THEN 'OK'
WHEN E.ESTADO=1 THEN 'NO FUNCIONAL'
WHEN E.ESTADO=2 THEN 'EN MANTENIMIENTO'
WHEN E.ESTADO=0 THEN 'DEVUELTO' END ESTADO,COUNT(*) CANTIDAD
FROM EQUIPAMIENTO E
JOIN AMBIENTE A
USING(IDAMBIENTE)
GROUP BY E.IDAMBIENTE,E.NOMBRE;
CREATE VIEW VEQUIPAMIENTO AS
SELECT E.IDAMBIENTE,A.NOMBRE AMBIENTE,E.ESTACION,E.NOMBRE TIPO,CASE WHEN E.ESTADO=0 THEN 'OK'
WHEN E.ESTADO=1 THEN 'NO FUNCIONAL'
WHEN E.ESTADO=2 THEN 'EN MANTENIMIENTO'
WHEN E.ESTADO=3 THEN 'DEVUELTO' END ESTADO
FROM EQUIPAMIENTO E
JOIN AMBIENTE A
USING(IDAMBIENTE)
ORDER BY 3;
CREATE VIEW VNOVEDADUNO AS
SELECT * FROM NOVEDADES N
JOIN  AMBIENTE A
USING(IDAMBIENTE)
JOIN USUARIO U
ON U.IDUSUARIO=A.IDCUENTADANTE;
CREATE VIEW vambiente as
select n.idnovedades,
n.idambiente,
a.idcuentadante,
a.nombre AMBIENTE,
n.PADRE,
n.fecha,n.descripcion,CASE WHEN n.estado=0 THEN 'ABIERTA'
WHEN n.estado=1 THEN 'PROCESO'
WHEN n.estado=2 THEN 'CERRADA' END ESTADO,c.nombre CUENTADANTE from novedades n
join ambiente a  
using(idambiente)
join usuario c
on(a.idcuentadante=c.idusuario);
COMMIT;
